version: '3.8'

services:
  web:
    build: .
    ports:
      - "5001:5000"
    volumes:
      - ./instance:/app/instance   # Mount a volume for SQLite database
    environment:
      FLASK_ENV: development
