version: '3.8'

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5000"  # Adjusted to avoid conflicts
    volumes:
      - .:/app/api   # Mapping your local directory to the container
    environment:
      FLASK_ENV: development
